name: Verificação de HTML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  html-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Rodar verificação nos arquivos HTML
        run: htmlhint "**/*.html"
